export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const GET_AFFIRMATION = "GET_AFFIRMATION"
export const GET_JOURNAL_ENTRIES = "GET_JOURNAL_ENTRIES"
export const GET_USER_PROFILE = "GET_USER_PROFILE"